apiVersion: v1
kind: ConfigMap
metadata:
  name: msa-config
  namespace: msa-platform
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  JWT_SECRET: "your-256-bit-secret-key-for-jwt-token-generation-min-32-chars"
  # Gmail SMTP 설정
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  # MinIO 설정
  MINIO_ENABLED: "true"
  MINIO_ENDPOINT: "http://minio.msa.svc.cluster.local:9000"
  MINIO_ACCESS_KEY: "minio"
  MINIO_SECRET_KEY: "minio123!"
  MINIO_BUCKET: "images"
