apiVersion: apps/v1
kind: Deployment
metadata:
  name: wedding-service
  namespace: msa-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wedding-service
  template:
    metadata:
      labels:
        app: wedding-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: jun
      containers:
        - name: wedding-service
          image: 100.67.243.29:30500/wedding-service:latest
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/wedding_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: msa-secrets
                  key: MYSQL_PASSWORD
          envFrom:
            - configMapRef:
                name: msa-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: wedding-service
  namespace: msa-platform
spec:
  selector:
    app: wedding-service
  ports:
    - port: 8089
